SPOTIFY_API_BASE_URL = "https://api.spotify.com/v1"
SPOTIFY_CURRENT_USER_BASE_URL = f"{SPOTIFY_API_BASE_URL}/me"
IDS = "ids"
TRACKS = "tracks"
ITEMS = "items"
TIME_RANGE = "time_range"
LIMIT = "limit"
