name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.head_commit.message }}
          prerelease: false
          files: |
            *.jar
