name: release

on:
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Filter files changed in PR
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          spotipyio:
            - 'spotipyio/**'

    - name: Get version from pyproject.toml
      id: get_version
      run: |
        PACKAGE_VERSION="v$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml)"
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

    - name: Bump version and push tag
#      if: steps.filter.outputs.spotipyio == 'true'
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ env.PACKAGE_VERSION }}

    - name: Create release
#      if: steps.filter.outputs.spotipyio == 'true'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        title: ${{ github.event.head_commit.message }}
        prerelease: false
        files: |
          *.gz
