name: release

on:
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Filter files changed in PR
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          spotipyio:
            - 'spotipyio/**'

    - name: Bump version and push tag
      if: steps.filter.outputs.spotipyio == 'true'
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: v$(shell sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml)
